# Generated by Django 4.1.5 on 2023-02-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0003_prettynum_alter_userinfo_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=18, verbose_name='密码')),
            ],
        ),
        migrations.AlterField(
            model_name='prettynum',
            name='price',
            field=models.IntegerField(verbose_name='价格'),
        ),
    ]
