# Generated by Django 4.1.5 on 2023-02-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0004_admin_alter_prettynum_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=16, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='pwd',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
    ]
